version: '3.3'
services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    networks:
      - planning
  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8082:8082"
    depends_on:
      - db
    networks:
      - planning
  app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "8083:80"
    depends_on:
      - api
    networks:
      - planning
networks:
  planning:
    driver: bridge