// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	entity "task-manager/internal/model/entity"

	mock "github.com/stretchr/testify/mock"
)

// IDeveloperService is an autogenerated mock type for the IDeveloperService type
type IDeveloperService struct {
	mock.Mock
}

// GetDevelopers provides a mock function with given fields:
func (_m *IDeveloperService) GetDevelopers() ([]entity.Developer, error) {
	ret := _m.Called()

	var r0 []entity.Developer
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.Developer, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.Developer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Developer)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDevelopersAndTasks provides a mock function with given fields:
func (_m *IDeveloperService) GetDevelopersAndTasks() ([]entity.Developer, error) {
	ret := _m.Called()

	var r0 []entity.Developer
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.Developer, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.Developer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Developer)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIDeveloperService interface {
	mock.TestingT
	Cleanup(func())
}

// NewIDeveloperService creates a new instance of IDeveloperService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIDeveloperService(t mockConstructorTestingTNewIDeveloperService) *IDeveloperService {
	mock := &IDeveloperService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
