// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	fiber "github.com/gofiber/fiber/v2"
	mock "github.com/stretchr/testify/mock"
)

// ITaskHandler is an autogenerated mock type for the ITaskHandler type
type ITaskHandler struct {
	mock.Mock
}

// GetPlanning provides a mock function with given fields: c
func (_m *ITaskHandler) GetPlanning(c *fiber.Ctx) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewITaskHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewITaskHandler creates a new instance of ITaskHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewITaskHandler(t mockConstructorTestingTNewITaskHandler) *ITaskHandler {
	mock := &ITaskHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
